services:
    webservice:
        image: "{{ image }}:{{ version }}"
        restart: always
        ports:
          - "{{ port }}:8080"
        environment:
          - SERVER_HOST=0.0.0.0
          - SERVER_PORT=8080
          - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
        networks:
          - tempo_default

networks:
    tempo_default:
        external: true
